### ISSUE TITLE
Unable to access MDS-NT1 with web minidisc

### ISSUE THREAD

**Issue by is-that-a-thing-now** [cybercase/netmd-js#6]
Hello,

I posted in the web minidisc github about this, but it seems like it would best fit here.

My MDS-NT1 is unable to be accessed by the web minidisc application.  It is visible, and I can start a connection, but it ends up with just a grey spinning circle forever.

It was mentioned that the vendor and product ID may help, they are as follow:
VendorID: 054c
ProductID: 0081

If I can help out in any other way please let me know.

**Comment by aaronamm** [comment]
@is-that-a-thing-now I have my own MDS-NT1 and it works well with Web MiniDisc.
I am not sure if your device has a hardware's problem. This is because it is quite an old item about ~20 years.
I used to have a broken NT1 and what I can do is only find another NT1 and use it as a replacement part.

I hope I have been of some help.

**Comment by is-that-a-thing-now** [comment]
Hello,

Yes, this is an older issue.  It has since been fixed thanks to D-9s work on adding decks. My deck works with web minidisc without issue now.

It worked find with good ol' SonicStage before, so I knew it wasn't a hardware issue anyway.

With Asivery's recent additions, pretty much everything should be working now.

**Comment by aaronamm** [comment]
@is-that-a-thing-now  Thanks for updating. I am glad it is a software part and it is fixed now.
